### PR TITLE
Added MySql option

### PR DESCRIPTION
**Pull request by zaubererty**
Added the option to run on a MySql database with the simple option of the database type.
The default still remains on PG

### CODE REVIEW

**Comment by x86dev** [comment]
Cool feature, thanks! I'll merge the PR as soon as I'm back from vacation.

I've also seen that you've committed the Fever API plugin to your branch -- which client(s) are you using this with? Might also worth integrating it to my branch :-)

**Comment by bobberb** [comment]
@x86dev does the code honor your ENV passes at all? Mine builds set to Fox and localhost...

**Comment by bobberb** [comment]
@x86dev specifically, a command such as 
`docker run -it --name ttrsspg -e DB_HOST=172.17.0.1 -e SU_USER=admin -e DB_USER=ttrss x86dev/docker-ttrss`

still results in 

`PHP Warning:  pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Address not available
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432? in /var/www/ttrss/classes/db/pgsql.php on line 21
PHP Warning:  pg_last_error(): No PostgreSQL link opened yet in /var/www/ttrss/classes/db/pgsql.php on line 24
Unable to connect to database (as fox to localhost, database fox):[18:01:31/310] Spawn interval: 120 sec
PHP Warning:  pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting`

**Comment by x86dev** [comment]
@bobberb I'll have to give this a try myself in a few days. Thanks for the pointer.

**Comment by zaubererty** [comment]
The "Fever API plugin" seam not to work. I can authenticate and sync the feeds but not the articles.
I'm currently debugging this ...

**Comment by thiesschneider** [comment]
Perhaps you can open the Issue tracker :)

**Comment by x86dev** [comment]
@thiesschneider Good idea, just done so :)

**Pull request merged**
