### PR TITLE
Set SELF_URL_PATH properly in config.php

### PR DESCRIPTION
**Pull request by rsilva4**

### CODE REVIEW

**Comment by x86dev** [comment]
Thanks for the patch!

**Comment by thiesschneider** [comment]
now it is not working anymore :/
`Please set SELF_URL_PATH to the correct value for your server (possible value:https://mydomain.xx)` 
In the logs of the container:
`2017-01-14 23:46:51,945 INFO gave up: ttrss-daemon entered FATAL state, too many start retries too quickly`

any ideas?

**Comment by abcminiuser** [comment]
This has also broken my Docker install in the same manner - could we have a rollback please? Alternatively, can we get a tagged build on Docker hub from before this patch?

**Comment by thiesschneider** [comment]
I think you have to add the env for the SELF_URL_PATH

**Comment by abcminiuser** [comment]
I think that's how it's *supposed* to work, but I tried a few combinations with no success.

For now I've pushed https://hub.docker.com/r/abcminiuser/docker-ttrss/ which is the current `master` branch here with the broken patch reverted - it's restored my local server until this gets sorted out.

**Comment by rsilva4** [comment]
Sorry guys, checking this now.

**Comment by rsilva4** [comment]
I've created a new PR that solves this issue https://github.com/x86dev/docker-ttrss/pull/5.

**Pull request merged**
